# Generated by Django 4.2.2 on 2023-07-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('account_type', models.CharField(choices=[('current_account', 'Current Account'), ('saving_account', 'Saving Account'), ('life_assurance', 'Life Assurance')], max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_manager.account')),
                ('category_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_1', to='finance_manager.category')),
                ('category_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_2', to='finance_manager.category')),
                ('category_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_3', to='finance_manager.category')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_manager.bank'),
        ),
    ]
