# Generated by Django 4.2.2 on 2023-07-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('current_account', 'Current Account'), ('saving_account', 'Saving Account'), ('life_assurance', 'Life Assurance')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
    ]
