# Generated by Django 4.2.2 on 2023-07-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0002_alter_account_account_type_delete_accounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_manager.subcategory'),
        ),
    ]
